// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCphP5d8nMkrtR7w3wzKnrU90Ovn6i-RrU',
    appId: '1:866444566884:web:763a3afe141c4498dd5a71',
    messagingSenderId: '866444566884',
    projectId: 'pcmc-app-2024-ravirajmane',
    authDomain: 'pcmc-app-2024-ravirajmane.firebaseapp.com',
    storageBucket: 'pcmc-app-2024-ravirajmane.firebasestorage.app',
    measurementId: 'G-JNP45L8GE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3a0oLxhS5hpRpmPbUTTqbGpPYGUOolqA',
    appId: '1:866444566884:android:905c838409cbe3c8dd5a71',
    messagingSenderId: '866444566884',
    projectId: 'pcmc-app-2024-ravirajmane',
    storageBucket: 'pcmc-app-2024-ravirajmane.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiPV9uSpSDSndTNyMl44DdsnmCo9upY7s',
    appId: '1:866444566884:ios:6caa7e60c3eb4e53dd5a71',
    messagingSenderId: '866444566884',
    projectId: 'pcmc-app-2024-ravirajmane',
    storageBucket: 'pcmc-app-2024-ravirajmane.firebasestorage.app',
    iosBundleId: 'com.example.mainUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiPV9uSpSDSndTNyMl44DdsnmCo9upY7s',
    appId: '1:866444566884:ios:6caa7e60c3eb4e53dd5a71',
    messagingSenderId: '866444566884',
    projectId: 'pcmc-app-2024-ravirajmane',
    storageBucket: 'pcmc-app-2024-ravirajmane.firebasestorage.app',
    iosBundleId: 'com.example.mainUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCphP5d8nMkrtR7w3wzKnrU90Ovn6i-RrU',
    appId: '1:866444566884:web:088a63504e25493fdd5a71',
    messagingSenderId: '866444566884',
    projectId: 'pcmc-app-2024-ravirajmane',
    authDomain: 'pcmc-app-2024-ravirajmane.firebaseapp.com',
    storageBucket: 'pcmc-app-2024-ravirajmane.firebasestorage.app',
    measurementId: 'G-1SM00DMF4Q',
  );

}