"""removed otp and notification

Revision ID: 9d23c6a63ac6
Revises: 
Create Date: 2025-10-03 15:22:58.444926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d23c6a63ac6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)

    if 'otp_token' in inspector.get_table_names():
        op.drop_table('otp_token')

    if 'notification_token' in inspector.get_table_names():
        op.drop_table('notification_token')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_voter_id', ['voter_id'])

    with op.batch_alter_table('workproof', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workproof', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('notification_token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('fcm_token', sa.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('otp', sa.VARCHAR(length=6), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
