"""Added nearby places

Revision ID: ae28e487fe6a
Revises: 9d23c6a63ac6
Create Date: 2025-10-29 10:13:21.138317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae28e487fe6a'
down_revision = '9d23c6a63ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nearby_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
       batch_op.create_unique_constraint('uq_user_voter_id', ['voter_id'])


    with op.batch_alter_table('workproof', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workproof', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.Column('role', sa.VARCHAR(length=11), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('address', sa.VARCHAR(length=256), nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(length=256), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('two_factor_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('voter_id', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['master_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('voter_id', name=op.f('uq_user_voter_id'))
    )
    op.drop_table('nearby_places')
    # ### end Alembic commands ###
