"""Added advertisements table with naming convention

Revision ID: c506e19ae4d4
Revises: dac5036ff377
Create Date: 2025-10-29 12:35:48.233551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c506e19ae4d4'
down_revision = 'dac5036ff377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_grievance_complaint_id'), ['complaint_id'])

    with op.batch_alter_table('master_config', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_master_config_key'), ['key'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_phone_number'), ['phone_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_voter_id'), ['voter_id'])

    from sqlalchemy.sql import table, column
    import sqlalchemy as sa

    workproof_table = table('workproof',
        column('file_type', sa.String)
    )

    op.execute(workproof_table.update().where(workproof_table.c.file_type == None).values(file_type='unknown'))
    op.execute("UPDATE workproof SET file_size = 0 WHERE file_size IS NULL;")

    with op.batch_alter_table('workproof', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workproof', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_voter_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_phone_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('master_config', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_master_config_key'), type_='unique')

    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_grievance_complaint_id'), type_='unique')

    # ### end Alembic commands ###
